# Generated by Django 5.0.6 on 2024-05-24 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
