# Generated by Django 5.0.6 on 2024-05-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
