# Generated by Django 5.0.6 on 2024-06-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Specification',
        ),
        migrations.AddField(
            model_name='product',
            name='Specification',
            field=models.ManyToManyField(blank=True, to='store.specification'),
        ),
    ]
