# Generated by Django 5.0.6 on 2024-05-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_productimage_delete_bio_delete_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='uploads/products'),
        ),
    ]
